"""Compatibility imports for hardy.literature.archives."""
from .literature.archives import (
    READ_CHUNK_BYTES,
    SINGLE_FILE_NAME,
    PDF_NAME,
    DRIVE,
    TAR_MAGIC_OFFSET,
    TAR_MAGIC,
    ArchiveError,
    Limits,
    DEFAULT_LIMITS,
    ExtractedFile,
    Extraction,
    _Bounded,
    kind_of,
    extract,
    member_path,
    _extract_tar,
    _prefixes,
    _no_file_on_the_way,
    _write_whole,
    _write,
    _clear,
)
