"""Compatibility imports for hardy.literature.archives."""
from hardy.literature.archives import DEFAULT_LIMITS as DEFAULT_LIMITS
from hardy.literature.archives import DRIVE as DRIVE
from hardy.literature.archives import PDF_NAME as PDF_NAME
from hardy.literature.archives import READ_CHUNK_BYTES as READ_CHUNK_BYTES
from hardy.literature.archives import SINGLE_FILE_NAME as SINGLE_FILE_NAME
from hardy.literature.archives import TAR_MAGIC as TAR_MAGIC
from hardy.literature.archives import TAR_MAGIC_OFFSET as TAR_MAGIC_OFFSET
from hardy.literature.archives import ArchiveError as ArchiveError
from hardy.literature.archives import ExtractedFile as ExtractedFile
from hardy.literature.archives import Extraction as Extraction
from hardy.literature.archives import Limits as Limits
from hardy.literature.archives import _Bounded as _Bounded
from hardy.literature.archives import _clear as _clear
from hardy.literature.archives import _extract_tar as _extract_tar
from hardy.literature.archives import _no_file_on_the_way as _no_file_on_the_way
from hardy.literature.archives import _prefixes as _prefixes
from hardy.literature.archives import _write as _write
from hardy.literature.archives import _write_whole as _write_whole
from hardy.literature.archives import extract as extract
from hardy.literature.archives import kind_of as kind_of
from hardy.literature.archives import member_path as member_path
