"""Compatibility imports for paper callers; ownership lives in hardy.literature."""
import urllib.request

from .literature.metadata import (
    ENDPOINT,
    SOURCE_ENDPOINT,
    MIN_INTERVAL_SECONDS,
    LOCK_SECONDS,
    QUERY_TTL_SECONDS,
    MAX_RESPONSE_BYTES,
    MAX_ARCHIVE_BYTES,
    READ_CHUNK_BYTES,
    DEFAULT_TIMEOUT_SECONDS,
    MAX_RESULTS,
    ABSTRACT_COLUMNS,
    USER_AGENT,
    ATOM,
    ARXIV,
    NEW_STYLE,
    OLD_STYLE,
    STRIP,
    ArxivError,
    ArxivId,
    parse_id,
    PaperRecord,
    _wrapped,
    _by_bytes,
    digest,
    SourceFile,
    SourceManifest,
    SOURCE_DIR,
    SOURCE_MANIFEST,
    SOURCE_ARCHIVE,
    Transport,
    _coherent,
    _stamp,
    _key,
    _entries,
    _decoded,
    _parsed,
    ERROR_ID,
    _entry,
    _text,
    _collapsed,
)
from .literature.library import (
    PaperLibrary,
)
from .literature.client import (
    _http,
    _narrow,
    ArxivClient,
)
