"""Compatibility imports for paper callers; ownership lives in hardy.literature."""

from hardy.literature.client import ArxivClient as ArxivClient
from hardy.literature.client import _http as _http
from hardy.literature.client import _narrow as _narrow
from hardy.literature.library import PaperLibrary as PaperLibrary
from hardy.literature.metadata import ABSTRACT_COLUMNS as ABSTRACT_COLUMNS
from hardy.literature.metadata import ARXIV as ARXIV
from hardy.literature.metadata import ATOM as ATOM
from hardy.literature.metadata import DEFAULT_TIMEOUT_SECONDS as DEFAULT_TIMEOUT_SECONDS
from hardy.literature.metadata import ENDPOINT as ENDPOINT
from hardy.literature.metadata import ERROR_ID as ERROR_ID
from hardy.literature.metadata import LOCK_SECONDS as LOCK_SECONDS
from hardy.literature.metadata import MAX_ARCHIVE_BYTES as MAX_ARCHIVE_BYTES
from hardy.literature.metadata import MAX_RESPONSE_BYTES as MAX_RESPONSE_BYTES
from hardy.literature.metadata import MAX_RESULTS as MAX_RESULTS
from hardy.literature.metadata import MIN_INTERVAL_SECONDS as MIN_INTERVAL_SECONDS
from hardy.literature.metadata import NEW_STYLE as NEW_STYLE
from hardy.literature.metadata import OLD_STYLE as OLD_STYLE
from hardy.literature.metadata import QUERY_TTL_SECONDS as QUERY_TTL_SECONDS
from hardy.literature.metadata import READ_CHUNK_BYTES as READ_CHUNK_BYTES
from hardy.literature.metadata import SOURCE_ARCHIVE as SOURCE_ARCHIVE
from hardy.literature.metadata import SOURCE_DIR as SOURCE_DIR
from hardy.literature.metadata import SOURCE_ENDPOINT as SOURCE_ENDPOINT
from hardy.literature.metadata import SOURCE_MANIFEST as SOURCE_MANIFEST
from hardy.literature.metadata import STRIP as STRIP
from hardy.literature.metadata import USER_AGENT as USER_AGENT
from hardy.literature.metadata import ArxivError as ArxivError
from hardy.literature.metadata import ArxivId as ArxivId
from hardy.literature.metadata import PaperRecord as PaperRecord
from hardy.literature.metadata import SourceFile as SourceFile
from hardy.literature.metadata import SourceManifest as SourceManifest
from hardy.literature.metadata import Transport as Transport
from hardy.literature.metadata import _by_bytes as _by_bytes
from hardy.literature.metadata import _coherent as _coherent
from hardy.literature.metadata import _collapsed as _collapsed
from hardy.literature.metadata import _decoded as _decoded
from hardy.literature.metadata import _entries as _entries
from hardy.literature.metadata import _entry as _entry
from hardy.literature.metadata import _key as _key
from hardy.literature.metadata import _parsed as _parsed
from hardy.literature.metadata import _stamp as _stamp
from hardy.literature.metadata import _text as _text
from hardy.literature.metadata import _wrapped as _wrapped
from hardy.literature.metadata import digest as digest
from hardy.literature.metadata import parse_id as parse_id
