"""Compatibility imports for hardy.literature.statements."""
from hardy.literature.statements import ALIASES as ALIASES
from hardy.literature.statements import BODY_MARKER as BODY_MARKER
from hardy.literature.statements import COMPONENT as COMPONENT
from hardy.literature.statements import KINDS as KINDS
from hardy.literature.statements import LABEL as LABEL
from hardy.literature.statements import MAX_STATEMENT_CHARACTERS as MAX_STATEMENT_CHARACTERS
from hardy.literature.statements import MAX_STATEMENTS as MAX_STATEMENTS
from hardy.literature.statements import OPENING as OPENING
from hardy.literature.statements import ROOT_MARKER as ROOT_MARKER
from hardy.literature.statements import AssumeError as AssumeError
from hardy.literature.statements import Minted as Minted
from hardy.literature.statements import Statement as Statement
from hardy.literature.statements import Survey as Survey
from hardy.literature.statements import _comment_safe as _comment_safe
from hardy.literature.statements import _docstring as _docstring
from hardy.literature.statements import _executable as _executable
from hardy.literature.statements import _from_pages as _from_pages
from hardy.literature.statements import _included_anywhere as _included_anywhere
from hardy.literature.statements import _kind_of as _kind_of
from hardy.literature.statements import _pages as _pages
from hardy.literature.statements import _read_pages as _read_pages
from hardy.literature.statements import _tidy as _tidy
from hardy.literature.statements import find as find
from hardy.literature.statements import inventory as inventory
from hardy.literature.statements import module_path_for as module_path_for
from hardy.literature.statements import namespace_for as namespace_for
from hardy.literature.statements import render_module as render_module
from hardy.literature.statements import root_of as root_of
from hardy.literature.statements import roots_of as roots_of
from hardy.literature.statements import survey as survey
