"""Export a CAS session, and check the export reproduces it.

A session is a live kernel; a script is a list of cells. They are not the same
object, and they drift: a cell that errored partway through may already have
mutated the namespace, and it is recorded but never accepted, so it will not
appear in the script. From that moment the running session and the exportable
script can disagree without anything saying so.

Hardy cannot prevent that. What it can do is refuse to pretend. Export does two
independent checks and publishes both.

The first replays every accepted cell in a fresh kernel and compares stdout,
stderr, and the value repr against what the live session recorded. That is a
statement about the *cells*.

The second runs the rendered script — the actual published file, as a
subprocess, exactly as a reader would — and compares its transcript against the
same record. That is a statement about the *artifact*, and it is not implied by
the first: a kernel evaluates a trailing expression and reports its value where
a script discards it, and a construct that is legal at the head of a cell can be
illegal in the middle of a file. Until the file has been run there is no
evidence about what running the file does, so `reproduces` requires both.

A diverged or unverified export is still written — a notebook marked `diverged`
is more useful than no notebook, and `DESIGN.md` asks for useful partial
artifacts over silence.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

from .cas import (
    CasError,
    CasSession,
    CellRecord,
    replay_in_fresh_kernel,
    reproduces,
    run_exported_script,
)
from .domain import FrozenModel
from .layout import CAS_SCRATCH, WriteGuard

WARNING = (
    "Generated by Hardy from a computer algebra session. Nothing here was run in a "
    "sandbox: execute it only in a disposable environment you trust."
)

Verdict = Literal["verified", "diverged", "failed", "unverified"]


class CellVerdict(FrozenModel):
    seq: int
    verdict: Verdict
    detail: str = ""


class ExportReport(FrozenModel):
    script_path: str
    notebook_path: str
    manifest_path: str
    backend: str
    verified: int = 0
    diverged: int = 0
    failed: int = 0
    unverified: int = 0
    verdicts: tuple[CellVerdict, ...] = ()
    # The rendered script, executed. Separate from the per-cell counts because
    # it answers a different question, and because a reader who only sees "2
    # verified" would otherwise take it for an answer to this one.
    script_verdict: Verdict = "unverified"
    script_detail: str = ""

    @property
    def reproduces(self) -> bool:
        return (
            self.diverged == 0
            and self.failed == 0
            and self.unverified == 0
            and self.script_verdict == "verified"
        )


def _verdicts(cells: tuple[CellRecord, ...], outcomes: list[Any]) -> list[CellVerdict]:
    verdicts = []
    for record, outcome in zip(cells, outcomes, strict=True):
        if outcome is None:
            verdicts.append(
                CellVerdict(seq=record.seq, verdict="unverified", detail="not reached")
            )
        elif outcome.status != "ok":
            verdicts.append(
                CellVerdict(
                    seq=record.seq,
                    verdict="failed",
                    detail=f"replay {outcome.status}: {(outcome.stderr or outcome.stdout).strip()[:160]}",
                )
            )
        elif not reproduces(record, outcome):
            verdicts.append(
                CellVerdict(
                    seq=record.seq,
                    verdict="diverged",
                    detail="replay produced different output",
                )
            )
        elif record.capture_truncated or outcome.capture_truncated:
            # The prefixes match and nothing is known about the rest. Calling
            # that "verified" would let `reproduces` claim complete reproduction
            # on evidence that stops at `cas_output_bytes`; AGENTS.md asks for a
            # partial result to state its limits rather than round itself up.
            verdicts.append(
                CellVerdict(
                    seq=record.seq,
                    verdict="unverified",
                    detail=(
                        "capture truncated at cas_output_bytes: the retained prefixes "
                        "match, and the discarded tails could not be compared"
                    ),
                )
            )
        else:
            verdicts.append(CellVerdict(seq=record.seq, verdict="verified"))
    return verdicts


def _content_lines(text: str) -> list[str]:
    """The lines carrying content, with trailing whitespace removed.

    Leading whitespace is kept. `normalise` stopped discarding it because the
    notebook preserves it and indentation is content in every language Hardy
    drives; this must not put that hole back on the script's side.

    Blank lines are dropped, and that is the one thing this comparison gives
    up. A recorded capture starts and ends at a cell's own markers, while the
    script has no cell boundaries in it at all, so the interpreter lays the
    vertical space between one cell and the next out differently by
    construction. What survives is every content line, in order.
    """
    return [line.rstrip() for line in text.splitlines() if line.strip()]


def _appears_in_order(actual: list[str], expected: list[str]) -> bool:
    """Whether `expected` occurs inside `actual` as one uninterrupted run.

    Not equality. An interpreter fed a whole file writes its own chrome around
    the transcript — a startup banner in front of it, a final prompt behind it —
    which says nothing about whether the session reproduced. Nothing is
    tolerated *between* the expected lines, so a missing, extra, or reordered
    line anywhere inside the session's own output still fails.
    """
    if not expected:
        return True
    width = len(expected)
    return any(actual[at : at + width] == expected for at in range(len(actual) - width + 1))


def _expected_transcript(cells: tuple[CellRecord, ...]) -> tuple[str, str]:
    """What a faithful run of the script prints, assembled from the record.

    A cell's value is part of its stdout here because that is where a script
    puts it: the driver reports `value_repr` in its own field, and
    `SympyBackend.render_cell` emits the `sys.displayhook` call that turns it
    into a printed line. Sentinel backends print values themselves and record
    nothing in `value_repr`, so the same assembly is right for them too.
    """
    out: list[str] = []
    err: list[str] = []
    for record in cells:
        out.append(record.stdout)
        if record.value_repr:
            out.append(record.value_repr + "\n")
        err.append(record.stderr)
    return "".join(out), "".join(err)


EXCERPT_LINES = 6
EXCERPT_LINE_CHARS = 120
EXCERPT_CHARS = 400


def _excerpt(lines: list[str] | str) -> str:
    """A quotable fragment of a transcript, small enough to publish.

    `script_detail` is copied into `export.json`, into the notebook's metadata,
    and into whatever the model or the CLI prints. A recorded line is allowed to
    be `cas_output_bytes` long, so quoting even a handful verbatim can make the
    detail larger than either artifact it is describing.
    """
    if isinstance(lines, str):
        return lines[:EXCERPT_CHARS] + ("…" if len(lines) > EXCERPT_CHARS else "")
    clipped = [
        line[:EXCERPT_LINE_CHARS] + ("…" if len(line) > EXCERPT_LINE_CHARS else "")
        for line in lines[:EXCERPT_LINES]
    ]
    rendered = repr(clipped)
    if len(lines) > EXCERPT_LINES:
        rendered += f" (+{len(lines) - EXCERPT_LINES} more line(s))"
    return rendered[:EXCERPT_CHARS]


def _one_line(text: str) -> str:
    """An excerpt with no newline left in it, for quoting into a comment.

    A comment ends at the first newline in every language Hardy drives, so
    anything written into one has to be flattened first. `_verdicts` builds a
    `failed` detail out of the replay's stderr, and for the default backend
    that is a traceback: emitted as one comment line, its second line onward
    landed in the published script as *source*, and the file died with
    `SyntaxError: unexpected indent` before it reached the first cell. The
    drift this module exists to report was reported by corrupting the artifact
    it reports on, and Hardy's own check then blamed the session for a syntax
    error that was Hardy's.

    `str.split()` with no argument splits on every character Python considers
    whitespace, which is a superset of the line terminators any of these
    interpreters recognise.
    """
    return _excerpt(" ".join(text.split()))


#: Named in `layout` rather than here, so the `.gitignore` this layout writes
#: names the same two directories these calls create. They were reset before
#: every export and never removed, sitting inside a `cas/` that IS versioned
#: and matched by no ignore rule -- a kernel's scratch output waiting for the
#: next `git add`. Two spellings of one name is how that happened.
REPLAY, SCRIPT_RUN = CAS_SCRATCH


def _scratch(directory: Path, name: str) -> Path:
    """An empty directory called `name`, proven to be inside `directory`.

    Both scratch trees an export makes are the working directory of a kernel
    running the user's own cells, which write files. A repository that ships
    `cas/replay` as a symlink would have those cells run -- and write --
    wherever it points, and `shutil.rmtree(..., ignore_errors=True)` says
    nothing when it declines to remove a link. `WriteGuard` refuses it instead,
    with the path and where it led.
    """
    target = directory / name
    shutil.rmtree(target, ignore_errors=True)
    return WriteGuard(target, create=True).directory


def _verify_script(
    session: CasSession, cells: tuple[CellRecord, ...], script: Path, directory: Path
) -> tuple[Verdict, str]:
    """Run the published file and say whether it reproduced the session.

    Billed to the session budget like every other kernel an export starts, and
    bounded by what is left of it: an export must not be a way to buy time the
    session no longer has.
    """
    remaining = session.remaining_seconds
    if remaining <= 0:
        return "unverified", "the session budget ran out before the script could be run"
    truncated_cells = [record.seq for record in cells if record.capture_truncated]

    # Fresh every time: a script that writes a file must be seen to create it,
    # not to find it left behind by the previous export.
    run_directory = _scratch(directory, SCRIPT_RUN)
    started = time.monotonic()
    try:
        run = run_exported_script(
            backend=session.backend,
            command=session.command,
            script=script,
            cwd=run_directory,
            timeout=remaining,
            max_output_bytes=session.limits.cas_output_bytes,
        )
    except CasError as error:
        session.charge(time.monotonic() - started)
        return "failed", str(error)
    session.charge(time.monotonic() - started)

    if run.timed_out:
        return "failed", f"the script did not finish within {remaining:g}s"
    if run.returncode:
        return "failed", f"the script exited {run.returncode}: {_excerpt(run.stderr.strip())}"

    # The file itself is what a line-oriented interpreter was fed, and what it
    # echoes back into its own transcript -- including Hardy's header and the
    # per-cell notes, which the session never printed and which sit between one
    # cell's output and the next.
    fed = (
        script.read_text(encoding="utf-8", errors="replace")
        if getattr(session.backend, "script_stdin", False)
        else ""
    )
    stdout = session.backend.sanitize(run.stdout, fed)
    pattern = getattr(session.backend, "error_pattern", None)
    if pattern is not None and (pattern.search(stdout) or pattern.search(run.stderr)):
        # A sentinel interpreter reports an error and carries on with the next
        # line, so a broken script still exits 0. The banner is the exit code.
        return "failed", "the script printed an error banner"

    # Everything above is a claim the evidence supports whatever was truncated:
    # the file ran, it exited 0, and no banner appeared in what was read.
    # Comparing transcripts is not, and this is the point at which a missing
    # tail stops being survivable. `diverged` is as much an affirmative claim as
    # `verified` -- "the script printed something else" about bytes Hardy never
    # read is the same rounding-up the truncated-cell verdict refuses, pointed
    # the other way.
    if run.capture_truncated:
        return "unverified", (
            "the script's own output passed cas_output_bytes, so its transcript "
            "could not be compared against the record"
        )
    if truncated_cells:
        return "unverified", (
            f"cell(s) {truncated_cells} were recorded from a truncated capture, so "
            "there is no complete transcript to compare the script against"
        )

    expected_out, expected_err = _expected_transcript(cells)
    for stream, actual, expected in (
        ("output", stdout, expected_out),
        ("stderr", run.stderr, expected_err),
    ):
        got, want = _content_lines(actual), _content_lines(expected)
        if not _appears_in_order(got, want):
            # The excerpts are here so a reader — or a CI log — can see *what*
            # differed without re-running anything. A verdict of "diverged" with
            # no evidence attached is another thing taken on trust. They are cut
            # to a readable size: a recorded line may be `cas_output_bytes` long,
            # and this detail is copied into export.json and the notebook, where
            # a verbatim pair of transcripts would dwarf the artifact.
            return "diverged", (
                f"the script's {stream} is not the {stream} the session recorded; "
                f"recorded {_excerpt(want)}, script printed {_excerpt(got)}"
            )
    return "verified", ""


def render_script(
    session: CasSession,
    cells: tuple[CellRecord, ...],
    verdicts: list[CellVerdict],
) -> str:
    """Write the accepted cells out as a file that behaves the way they did.

    The header says what was checked and stops there. It cannot report the
    verdict on running this file, because the verdict is obtained by running
    exactly these bytes: a header that named its own result would describe a
    file that no longer existed by the time it was written. `export.json` and
    the notebook carry it instead, and the header points at them.
    """
    backend = session.backend
    mark = backend.comment
    replayed = sum(1 for verdict in verdicts if verdict.verdict == "verified")
    # Flattened for the same reason the per-cell notes below are: a version a
    # backend reported over more than one line would break the header out of
    # its comment exactly as a traceback broke the cell notes out of theirs.
    version = _one_line(session.version or "") or "unknown version"
    lines = [
        f"{mark} {WARNING}",
        f"{mark} backend: {backend.name} {version}",
        f"{mark} exported: {datetime.now(UTC).isoformat(timespec='seconds')}",
        f"{mark} cells: {len(cells)}; {replayed} of them reproduced when replayed"
        " one at a time in a fresh kernel.",
        f"{mark} Whether this file as a whole reproduces the session is a separate"
        " question: Hardy runs it and records the answer as `script_verdict` in"
        " export.json.",
        "",
    ]
    if backend.preamble:
        lines += [backend.preamble, ""]
    for record, verdict in zip(cells, verdicts, strict=True):
        note = (
            ""
            if verdict.verdict == "verified"
            else f"  [{verdict.verdict}: {_one_line(verdict.detail)}]"
        )
        lines.append(f"{mark} --- cell {record.seq} ({record.author}){note}")
        lines.append(backend.render_cell(record.source).rstrip())
        lines.append("")
    return "\n".join(lines) + "\n"


def render_notebook(
    session: CasSession,
    cells: tuple[CellRecord, ...],
    verdicts: list[CellVerdict],
    script_verdict: tuple[Verdict, str] = ("unverified", "not run"),
) -> str:
    """nbformat v4, written directly.

    Hardy does not drive a Jupyter kernel — the Macaulay2 and Singular bridges
    are unmaintained — so the notebook is authored from the session's own
    record. For those backends the declared kernelspec may well name a kernel
    the reader does not have; it is a faithful record either way.
    """
    backend = session.backend
    notebook_cells: list[dict[str, Any]] = []
    for record, verdict in zip(cells, verdicts, strict=True):
        outputs: list[dict[str, Any]] = []
        if record.stdout:
            outputs.append(
                {"output_type": "stream", "name": "stdout", "text": record.stdout.splitlines(True)}
            )
        if record.stderr:
            outputs.append(
                {"output_type": "stream", "name": "stderr", "text": record.stderr.splitlines(True)}
            )
        if record.value_repr:
            outputs.append(
                {
                    "output_type": "execute_result",
                    "execution_count": record.seq,
                    "data": {"text/plain": record.value_repr.splitlines(True)},
                    "metadata": {},
                }
            )
        notebook_cells.append(
            {
                "cell_type": "code",
                "execution_count": record.seq,
                "metadata": {
                    "hardy": {
                        "seq": record.seq,
                        "author": record.author,
                        "verification": verdict.verdict,
                        "detail": verdict.detail,
                        "capture_truncated": record.capture_truncated,
                    }
                },
                "outputs": outputs,
                "source": record.source.splitlines(True),
            }
        )
    notebook = {
        "cells": notebook_cells,
        "metadata": {
            "hardy": {
                "warning": WARNING,
                "backend": backend.name,
                "version": session.version,
                # About the sibling script, not this notebook: the notebook
                # carries the recorded outputs and is honest by construction,
                # and a reader holding both should not have to open export.json
                # to find out which of the two was checked by execution.
                "script_verification": {
                    "verdict": script_verdict[0],
                    "detail": script_verdict[1],
                },
            },
            "kernelspec": {
                "display_name": backend.name,
                "language": backend.language,
                "name": backend.kernel_name,
            },
            "language_info": {"name": backend.language},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def export_session(session: CasSession, directory: Path) -> ExportReport:
    """Render, replay, compare, and publish the pair under one manifest."""
    cells = session.accepted()
    if not cells:
        raise CasError("nothing to export: the session has no accepted cells")

    # Every file this function publishes goes through this guard, which proves
    # at each write that `directory` is still the problem's own `cas/` and not
    # a symlink pointing out of it. `Layout.ensure` checked that when the
    # project opened; an export happens later, and a clone is free to ship the
    # link that makes "later" the interesting moment.
    guard = WriteGuard(directory, create=True)
    # Fresh every time, on the same rule `_verify_script` applies to
    # `script-run`: a replay that starts in the previous export's leftovers is
    # not the fresh kernel this check says it is, and a cell that writes a file
    # must be seen to create it rather than to find it.
    replay_directory = _scratch(directory, REPLAY)
    outcomes = replay_in_fresh_kernel(
        backend=session.backend,
        command=session.command,
        cells=cells,
        limits=session.limits,
        cwd=replay_directory,
        # An export is the session spending its own budget in a second kernel.
        # Bounded by what is left, and billed for what it uses, so a session
        # cannot exceed `cas_session_seconds` by exporting repeatedly. Cells
        # the remaining budget does not reach come back `unverified`, which is
        # what `docs/.../interactive-cas-design.md` already promised.
        budget_seconds=session.remaining_seconds,
        charge=session.charge,
    )
    verdicts = _verdicts(cells, outcomes)

    script_path = directory / f"session{session.backend.script_suffix}"
    notebook_path = directory / "session.ipynb"
    script = render_script(session, cells, verdicts).encode("utf-8")
    # The script is published before it is checked, because the thing checked
    # has to be the thing published: these exact bytes are what gets run.
    guard.write_bytes(script_path.name, script)
    try:
        script_verdict = _verify_script(session, cells, script_path, directory)
    except Exception as error:  # noqa: BLE001 - see below
        # Deliberately everything. `DESIGN.md` requires a partial export to be
        # written and marked rather than withheld, and the check is the *last*
        # thing that should be able to take the notebook and the manifest with
        # it: a session that cannot say whether its script runs is strictly
        # better off than one with no artifacts at all. A verdict of
        # `unverified` naming the failure is what that costs.
        script_verdict = ("unverified", _excerpt(f"the script could not be checked: {error!r}"))
    notebook = render_notebook(session, cells, verdicts, script_verdict).encode("utf-8")
    guard.write_bytes(notebook_path.name, notebook)

    counts = {name: 0 for name in ("verified", "diverged", "failed", "unverified")}
    for verdict in verdicts:
        counts[verdict.verdict] += 1
    report = ExportReport(
        script_path=script_path.as_posix(),
        notebook_path=notebook_path.as_posix(),
        manifest_path=(directory / "export.json").as_posix(),
        backend=session.backend.name,
        verdicts=tuple(verdicts),
        script_verdict=script_verdict[0],
        script_detail=script_verdict[1],
        **counts,
    )
    # Written last, and recording both digests. Two atomic writes are not one
    # atomic write: a crash between them would leave a fresh script beside a
    # stale notebook, and only this manifest makes that detectable.
    manifest = {
        "exported_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "backend": session.backend.name,
        "version": session.version,
        "counts": counts,
        "script_verdict": script_verdict[0],
        "script_detail": script_verdict[1],
        "files": {
            script_path.name: hashlib.sha256(script).hexdigest(),
            notebook_path.name: hashlib.sha256(notebook).hexdigest(),
        },
        "verdicts": [verdict.model_dump(mode="json") for verdict in verdicts],
    }
    guard.write_bytes(
        "export.json",
        (json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8"),
    )
    return report
