"""Export a CAS session, and check the export reproduces it.

A session is a live kernel; a script is a list of cells. They are not the same
object, and they drift: a cell that errored partway through may already have
mutated the namespace, and it is recorded but never accepted, so it will not
appear in the script. From that moment the running session and the exportable
script can disagree without anything saying so.

Hardy cannot prevent that. What it can do is refuse to pretend. Export replays
every accepted cell in a fresh kernel and compares stdout, stderr, and the
value repr against what the live session recorded, then writes the verdict into
both artifacts. A diverged export is still written — a notebook marked
`diverged` is more useful than no notebook, and `DESIGN.md` asks for useful
partial artifacts over silence.
"""

from __future__ import annotations

import hashlib
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

from .cas import CasError, CasSession, CellRecord, replay_in_fresh_kernel, reproduces
from .domain import FrozenModel
from .storage import atomic_write_bytes

WARNING = (
    "Generated by Hardy from a computer algebra session. Nothing here was run in a "
    "sandbox: execute it only in a disposable environment you trust."
)

Verdict = Literal["verified", "diverged", "failed", "unverified"]


class CellVerdict(FrozenModel):
    seq: int
    verdict: Verdict
    detail: str = ""


class ExportReport(FrozenModel):
    script_path: str
    notebook_path: str
    manifest_path: str
    backend: str
    verified: int = 0
    diverged: int = 0
    failed: int = 0
    unverified: int = 0
    verdicts: tuple[CellVerdict, ...] = ()

    @property
    def reproduces(self) -> bool:
        return self.diverged == 0 and self.failed == 0 and self.unverified == 0


def _verdicts(cells: tuple[CellRecord, ...], outcomes: list[Any]) -> list[CellVerdict]:
    verdicts = []
    for record, outcome in zip(cells, outcomes, strict=True):
        if outcome is None:
            verdicts.append(
                CellVerdict(seq=record.seq, verdict="unverified", detail="not reached")
            )
        elif outcome.status != "ok":
            verdicts.append(
                CellVerdict(
                    seq=record.seq,
                    verdict="failed",
                    detail=f"replay {outcome.status}: {(outcome.stderr or outcome.stdout).strip()[:160]}",
                )
            )
        elif reproduces(record, outcome):
            verdicts.append(CellVerdict(seq=record.seq, verdict="verified"))
        else:
            verdicts.append(
                CellVerdict(
                    seq=record.seq,
                    verdict="diverged",
                    detail="replay produced different output",
                )
            )
    return verdicts


def render_script(
    session: CasSession,
    cells: tuple[CellRecord, ...],
    verdicts: list[CellVerdict],
) -> str:
    backend = session.backend
    mark = backend.comment
    lines = [
        f"{mark} {WARNING}",
        f"{mark} backend: {backend.name} {session.version or 'unknown version'}",
        f"{mark} exported: {datetime.now(UTC).isoformat(timespec='seconds')}",
        f"{mark} cells: {len(cells)}"
        f" ({sum(1 for v in verdicts if v.verdict == 'verified')} verified on replay)",
        "",
    ]
    if backend.preamble:
        lines += [backend.preamble, ""]
    for record, verdict in zip(cells, verdicts, strict=True):
        note = "" if verdict.verdict == "verified" else f"  [{verdict.verdict}: {verdict.detail}]"
        lines.append(f"{mark} --- cell {record.seq} ({record.author}){note}")
        lines.append(record.source.rstrip())
        lines.append("")
    return "\n".join(lines) + "\n"


def render_notebook(
    session: CasSession,
    cells: tuple[CellRecord, ...],
    verdicts: list[CellVerdict],
) -> str:
    """nbformat v4, written directly.

    Hardy does not drive a Jupyter kernel — the Macaulay2 and Singular bridges
    are unmaintained — so the notebook is authored from the session's own
    record. For those backends the declared kernelspec may well name a kernel
    the reader does not have; it is a faithful record either way.
    """
    backend = session.backend
    notebook_cells: list[dict[str, Any]] = []
    for record, verdict in zip(cells, verdicts, strict=True):
        outputs: list[dict[str, Any]] = []
        if record.stdout:
            outputs.append(
                {"output_type": "stream", "name": "stdout", "text": record.stdout.splitlines(True)}
            )
        if record.stderr:
            outputs.append(
                {"output_type": "stream", "name": "stderr", "text": record.stderr.splitlines(True)}
            )
        if record.value_repr:
            outputs.append(
                {
                    "output_type": "execute_result",
                    "execution_count": record.seq,
                    "data": {"text/plain": record.value_repr.splitlines(True)},
                    "metadata": {},
                }
            )
        notebook_cells.append(
            {
                "cell_type": "code",
                "execution_count": record.seq,
                "metadata": {
                    "hardy": {
                        "seq": record.seq,
                        "author": record.author,
                        "verification": verdict.verdict,
                        "detail": verdict.detail,
                        "capture_truncated": record.capture_truncated,
                    }
                },
                "outputs": outputs,
                "source": record.source.splitlines(True),
            }
        )
    notebook = {
        "cells": notebook_cells,
        "metadata": {
            "hardy": {
                "warning": WARNING,
                "backend": backend.name,
                "version": session.version,
            },
            "kernelspec": {
                "display_name": backend.name,
                "language": backend.language,
                "name": backend.kernel_name,
            },
            "language_info": {"name": backend.language},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def export_session(session: CasSession, directory: Path) -> ExportReport:
    """Render, replay, compare, and publish the pair under one manifest."""
    cells = session.accepted()
    if not cells:
        raise CasError("nothing to export: the session has no accepted cells")

    directory.mkdir(parents=True, exist_ok=True)
    outcomes = replay_in_fresh_kernel(
        backend=session.backend,
        command=session.command,
        cells=cells,
        limits=session.limits,
        cwd=directory / "replay",
    )
    verdicts = _verdicts(cells, outcomes)

    script_path = directory / f"session{session.backend.script_suffix}"
    notebook_path = directory / "session.ipynb"
    script = render_script(session, cells, verdicts).encode("utf-8")
    notebook = render_notebook(session, cells, verdicts).encode("utf-8")
    atomic_write_bytes(script_path, script)
    atomic_write_bytes(notebook_path, notebook)

    counts = {name: 0 for name in ("verified", "diverged", "failed", "unverified")}
    for verdict in verdicts:
        counts[verdict.verdict] += 1
    report = ExportReport(
        script_path=script_path.as_posix(),
        notebook_path=notebook_path.as_posix(),
        manifest_path=(directory / "export.json").as_posix(),
        backend=session.backend.name,
        verdicts=tuple(verdicts),
        **counts,
    )
    # Written last, and recording both digests. Two atomic writes are not one
    # atomic write: a crash between them would leave a fresh script beside a
    # stale notebook, and only this manifest makes that detectable.
    manifest = {
        "exported_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "backend": session.backend.name,
        "version": session.version,
        "counts": counts,
        "files": {
            script_path.name: hashlib.sha256(script).hexdigest(),
            notebook_path.name: hashlib.sha256(notebook).hexdigest(),
        },
        "verdicts": [verdict.model_dump(mode="json") for verdict in verdicts],
    }
    atomic_write_bytes(
        directory / "export.json",
        (json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8"),
    )
    return report
