"""Export a CAS session, and check the export reproduces it.

A session is a live kernel; a script is a list of cells. They are not the same
object, and they drift: a cell that errored partway through may already have
mutated the namespace, and it is recorded but never accepted, so it will not
appear in the script. From that moment the running session and the exportable
script can disagree without anything saying so.

Hardy cannot prevent that. What it can do is refuse to pretend. Export does two
independent checks and publishes both.

The first replays every accepted cell in a fresh kernel and compares stdout,
stderr, and the value repr against what the live session recorded. That is a
statement about the *cells*.

The second runs the rendered script — the actual published file, as a
subprocess, exactly as a reader would — and compares its transcript against the
same record. That is a statement about the *artifact*, and it is not implied by
the first: a kernel evaluates a trailing expression and reports its value where
a script discards it, and a construct that is legal at the head of a cell can be
illegal in the middle of a file. Until the file has been run there is no
evidence about what running the file does, so `reproduces` requires both.

A diverged or unverified export is still written — a notebook marked `diverged`
is more useful than no notebook, and `DESIGN.md` asks for useful partial
artifacts over silence.
"""

from __future__ import annotations

import hashlib
import json
import secrets
import shutil
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

from .cas import (
    CasError,
    CasSession,
    CellRecord,
    replay_in_fresh_kernel,
    reproduces,
    run_exported_script,
    same_output,
    unobservable,
)
from .domain import FrozenModel
from .layout import CAS_SCRATCH, WriteGuard

WARNING = (
    "Generated by Hardy from a computer algebra session. Nothing here was run in a "
    "sandbox: execute it only in a disposable environment you trust."
)

Verdict = Literal["verified", "diverged", "failed", "unverified"]


class CellVerdict(FrozenModel):
    seq: int
    verdict: Verdict
    detail: str = ""


class ExportReport(FrozenModel):
    script_path: str
    notebook_path: str
    manifest_path: str
    backend: str
    verified: int = 0
    diverged: int = 0
    failed: int = 0
    unverified: int = 0
    verdicts: tuple[CellVerdict, ...] = ()
    # The rendered script, executed. Separate from the per-cell counts because
    # it answers a different question, and because a reader who only sees "2
    # verified" would otherwise take it for an answer to this one.
    script_verdict: Verdict = "unverified"
    script_detail: str = ""

    @property
    def reproduces(self) -> bool:
        return (
            self.diverged == 0
            and self.failed == 0
            and self.unverified == 0
            and self.script_verdict == "verified"
        )


def _verdicts(
    cells: tuple[CellRecord, ...], outcomes: list[Any], backend: Any = None
) -> list[CellVerdict]:
    # Whether a missing digest on these records means anything. On the default
    # backend it does: the protocol carries one, so its absence says Hardy
    # could not fingerprint that namespace. On a sentinel backend every record
    # is digestless and the absence says nothing at all, so drawing a verdict
    # from it would mark every Singular and Macaulay2 cell unverified forever.
    records_state = getattr(backend, "records_state", False)
    verdicts = []
    for record, outcome in zip(cells, outcomes, strict=True):
        if outcome is None:
            verdicts.append(
                CellVerdict(seq=record.seq, verdict="unverified", detail="not reached")
            )
        elif outcome.status != "ok":
            verdicts.append(
                CellVerdict(
                    seq=record.seq,
                    verdict="failed",
                    detail=f"replay {outcome.status}: {(outcome.stderr or outcome.stdout).strip()[:160]}",
                )
            )
        elif not reproduces(record, outcome):
            # Which comparison failed, not just that one did. A silent
            # `x = random.random()` reproduces every printed field and fails
            # only on the digest, and reporting that as "different output"
            # told `export.json` and the notebook the opposite of what
            # happened -- hiding exactly the state discrepancy the digest was
            # added to expose.
            verdicts.append(
                CellVerdict(
                    seq=record.seq,
                    verdict="diverged",
                    detail=(
                        "replay produced different output"
                        if not same_output(record, outcome)
                        else "replay reproduced the output and rebuilt a different namespace"
                    ),
                )
            )
        elif record.capture_truncated or outcome.capture_truncated:
            # The prefixes match and nothing is known about the rest. Calling
            # that "verified" would let `reproduces` claim complete reproduction
            # on evidence that stops at `cas_output_bytes`; AGENTS.md asks for a
            # partial result to state its limits rather than round itself up.
            verdicts.append(
                CellVerdict(
                    seq=record.seq,
                    verdict="unverified",
                    detail=(
                        "capture truncated at cas_output_bytes: the retained prefixes "
                        "match, and the discarded tails could not be compared"
                    ),
                )
            )
        elif records_state and unobservable(record):
            # The replay reproduced everything Hardy can see and nothing more.
            # `_restore` already refuses to call this a checked rebuild; an
            # export publishing the same replay as `verified` would be the
            # same overclaim on the other path.
            verdicts.append(
                CellVerdict(
                    seq=record.seq,
                    verdict="unverified",
                    detail=(
                        "output reproduced, state not compared: this kernel could not "
                        "fingerprint the namespace this cell left"
                    ),
                )
            )
        else:
            verdicts.append(CellVerdict(seq=record.seq, verdict="verified"))
    return verdicts


def _content_lines(text: str) -> list[str]:
    """The lines carrying content, with trailing whitespace removed.

    Leading whitespace is kept. `normalise` stopped discarding it because the
    notebook preserves it and indentation is content in every language Hardy
    drives; this must not put that hole back on the script's side.

    Blank lines are dropped, and that is the one thing this comparison gives
    up. A recorded capture starts and ends at a cell's own markers, while the
    script has no cell boundaries in it at all, so the interpreter lays the
    vertical space between one cell and the next out differently by
    construction. What survives is every content line, in order.
    """
    return [line.rstrip() for line in text.splitlines() if line.strip()]


TRANSCRIPT_BEGIN = "«hardy-transcript-begin»"
TRANSCRIPT_END = "«hardy-transcript-end»"
def completion_marker() -> str:
    """A line the published file prints as its own last statement.

    Evidence that the script *finished*, which the closing marker cannot give.
    That marker is an `atexit` callback -- which is what puts it out of reach
    of anything a cell can rebind, and also what makes it fire on
    `SystemExit(0)`: a first cell guarded by
    `if __name__ == "__main__": raise SystemExit(0)` is silent under the driver
    and ends the script under `python session.py`, so the markers went out
    around an empty transcript, the file exited 0, and an export reported
    reproduction for a run in which none of the later cells existed.

    A printed line rather than a flag a later statement sets. The flag was a
    name in the script's own namespace, so a cell could `append` to it and buy
    itself the finished marker; there is no name here to reach. It is fresh per
    export because a fixed sentinel is a string a cell may legitimately print
    -- which would have failed a faithful export on the strength of its output
    matching Hardy's own -- and because a constant is one a cell could type on
    purpose. A cell that reads its own source can still find this, exactly as
    it can find the markers; what it cannot do is collide with it by accident.

    Every way of failing to print it reports the run cut short: the statement
    never reached, `print` rebound to something that swallows it, `__import__`
    broken so the statement raises and the file exits non-zero.
    """
    return f"«hardy-transcript-finished-{secrets.token_hex(8)}»"


def _after_end_marker(text: str) -> str:
    """Whatever the script printed behind its own closing marker.

    Not nothing, necessarily, and not safely ignorable. A child the last cell
    spawned keeps the inherited descriptor open, so it can write after the
    file has finished and after the marker has gone out -- and slicing to the
    markers put those bytes outside the comparison, where an export could
    still call itself verified over output the session never saw. There is no
    later live cell to pin it on either, so nothing else would have noticed.
    """
    end = text.rfind(TRANSCRIPT_END)
    if end == -1:
        return ""
    return text[end + len(TRANSCRIPT_END) :]


def _between_markers(text: str) -> str | None:
    """The script's own transcript, cut out of whatever surrounded it.

    An interpreter fed a whole file writes its own chrome around what the file
    printed -- a startup banner in front of it, a prompt behind it -- and this
    comparison used to answer that by looking for the record *inside* the
    transcript rather than requiring the two to be equal. That accepted far
    too much. Extra output before or after the recorded lines still verified,
    and a session that recorded nothing at all accepted any output whatever:
    a cell guarded by `if __name__ == "__main__":` is silent under the driver,
    whose module name is not `__main__`, and prints from the published script,
    and the export called that reproduction.

    So the script says where its own transcript begins and ends, rather than
    Hardy guessing which lines an interpreter added. What falls outside the
    markers is by construction the interpreter's, and what falls between them
    has to be equal to the record, line for line.

    The first begin and the *last* end are taken. A cell is free to print
    either marker itself, and taking the outermost pair means doing so can
    only widen the region a cell's output has to match in -- never hide
    anything outside it.
    """
    start = text.find(TRANSCRIPT_BEGIN)
    end = text.rfind(TRANSCRIPT_END)
    if start == -1 or end == -1 or end < start:
        return None
    return text[start + len(TRANSCRIPT_BEGIN) : end]


def _expected_transcript(cells: tuple[CellRecord, ...]) -> tuple[str, str]:
    """What a faithful run of the script prints, assembled from the record.

    A cell's value is part of its stdout here because that is where a script
    puts it: the driver reports `value_repr` in its own field, and
    `SympyBackend.render_cell` emits the `sys.displayhook` call that turns it
    into a printed line. Sentinel backends print values themselves and record
    nothing in `value_repr`, so the same assembly is right for them too.
    """
    out: list[str] = []
    err: list[str] = []
    for record in cells:
        out.append(record.stdout)
        if record.value_repr:
            out.append(record.value_repr + "\n")
        err.append(record.stderr)
    return "".join(out), "".join(err)


def _markers(statements: tuple[str, ...], finished: str = "") -> list[str]:
    """Fill a backend's transcript-bracket templates with the actual markers."""
    return [
        statement.format(begin=TRANSCRIPT_BEGIN, end=TRANSCRIPT_END, finished=finished)
        for statement in statements
    ]


def _wants_completion(backend: Any) -> bool:
    """Whether this backend's last statement is the one that says it finished.

    Only where the closing marker is a shutdown hook. Singular and Macaulay2
    print theirs from the foot of the file, so an interpreter that stopped
    early never prints it and `_between_markers` already has nothing to cut.
    """
    return "{finished}" in "".join(getattr(backend, "transcript_epilogue", ()))


def _without_chrome(backend: Any, text: str) -> str:
    """Drop the lines an interpreter is *known* to write on its own account.

    stdout is bracketed by markers the script prints itself, which is the
    strongest form of this rule: what falls outside them is the interpreter's
    by construction. Hardy has no statement it can be sure of in all three
    backends' languages for writing to stderr, so that stream gets the weaker
    form -- chrome is removed only where it has been named, and everything
    left has to equal the record. No backend declares any yet, which makes
    stderr an exact comparison for all three. A line an interpreter turns out
    to write unbidden shows up as a `diverged` verdict quoting it, which is
    where it gets added -- rather than as an export quietly accepting whatever
    appeared.
    """
    patterns = getattr(backend, "script_stderr_chrome", ())
    if not patterns:
        return text
    return "\n".join(
        line
        for line in text.splitlines()
        if not any(pattern.match(line) for pattern in patterns)
    )


EXCERPT_LINES = 6
EXCERPT_LINE_CHARS = 120
EXCERPT_CHARS = 400


def _excerpt(lines: list[str] | str) -> str:
    """A quotable fragment of a transcript, small enough to publish.

    `script_detail` is copied into `export.json`, into the notebook's metadata,
    and into whatever the model or the CLI prints. A recorded line is allowed to
    be `cas_output_bytes` long, so quoting even a handful verbatim can make the
    detail larger than either artifact it is describing.
    """
    if isinstance(lines, str):
        return lines[:EXCERPT_CHARS] + ("…" if len(lines) > EXCERPT_CHARS else "")
    clipped = [
        line[:EXCERPT_LINE_CHARS] + ("…" if len(line) > EXCERPT_LINE_CHARS else "")
        for line in lines[:EXCERPT_LINES]
    ]
    rendered = repr(clipped)
    if len(lines) > EXCERPT_LINES:
        rendered += f" (+{len(lines) - EXCERPT_LINES} more line(s))"
    return rendered[:EXCERPT_CHARS]


def _one_line(text: str) -> str:
    """An excerpt with no newline left in it, for quoting into a comment.

    A comment ends at the first newline in every language Hardy drives, so
    anything written into one has to be flattened first. `_verdicts` builds a
    `failed` detail out of the replay's stderr, and for the default backend
    that is a traceback: emitted as one comment line, its second line onward
    landed in the published script as *source*, and the file died with
    `SyntaxError: unexpected indent` before it reached the first cell. The
    drift this module exists to report was reported by corrupting the artifact
    it reports on, and Hardy's own check then blamed the session for a syntax
    error that was Hardy's.

    `str.split()` with no argument splits on every character Python considers
    whitespace, which is a superset of the line terminators any of these
    interpreters recognise.
    """
    return _excerpt(" ".join(text.split()))


#: Named in `layout` rather than here, so the `.gitignore` this layout writes
#: names the same two directories these calls create. They were reset before
#: every export and never removed, sitting inside a `cas/` that IS versioned
#: and matched by no ignore rule -- a kernel's scratch output waiting for the
#: next `git add`. Two spellings of one name is how that happened.
REPLAY, SCRIPT_RUN = CAS_SCRATCH


def _scratch(directory: Path, name: str) -> Path:
    """An empty directory called `name`, proven to be inside `directory`.

    Both scratch trees an export makes are the working directory of a kernel
    running the user's own cells, which write files. A repository that ships
    `cas/replay` as a symlink would have those cells run -- and write --
    wherever it points, and `shutil.rmtree(..., ignore_errors=True)` says
    nothing when it declines to remove a link. `WriteGuard` refuses it instead,
    with the path and where it led.
    """
    target = directory / name
    shutil.rmtree(target, ignore_errors=True)
    return WriteGuard(target, create=True).directory


def _restore_published(script: Path, published: bytes) -> bool:
    """Put the published bytes back after a run that changed them.

    Through a guard, like every other write an export makes: `script` is a
    path an export built and a run has just demonstrated it is willing to
    interfere with, and a rebuilt path is exactly what the guard exists to
    refuse. A run that left a symlink there is one of the things it refuses,
    so this can fail -- and a failed restore has to be reported rather than
    swallowed, because it leaves an artifact the manifest's hash does not
    describe.
    """
    try:
        guard = WriteGuard(script.parent, create=False)
        guard.write_bytes(script.name, published)
    except Exception:
        return False
    return True


def _verify_script(
    session: CasSession,
    cells: tuple[CellRecord, ...],
    script: Path,
    directory: Path,
    completion: str = "",
) -> tuple[Verdict, str]:
    """Run the published file and say whether it reproduced the session.

    Billed to the session budget like every other kernel an export starts, and
    bounded by what is left of it: an export must not be a way to buy time the
    session no longer has.
    """
    remaining = session.remaining_seconds
    if remaining <= 0:
        return "unverified", "the session budget ran out before the script could be run"
    truncated_cells = [record.seq for record in cells if record.capture_truncated]

    # Fresh every time: a script that writes a file must be seen to create it,
    # not to find it left behind by the previous export.
    run_directory = _scratch(directory, SCRIPT_RUN)
    # The published file itself, at the path it was published to -- not a copy
    # somewhere else. Byte identity is not enough to make a copy stand in for
    # it, because moving a file changes `__file__`: a cell reading
    # `pathlib.Path(__file__).parent.name` branches one way under the check
    # and the other way when a reader runs the artifact, and the verdict would
    # then describe a run nobody will ever perform. Only the working directory
    # is moved aside, so what the run writes by a relative path lands in the
    # scratch tree; a run that writes relative to `__file__` writes beside the
    # artifact, which is what running the artifact does and what the check is
    # here to be honest about.
    #
    # What running it in place costs is the artifact: a cell is free to rewrite
    # or delete the path it was run from, and Python has already loaded the
    # module, so such a run still finishes and still matches the record. That
    # is answered below by putting the bytes back and refusing the verdict,
    # rather than by checking a file no reader will run.
    published = script.read_bytes()
    running = script
    started = time.monotonic()
    try:
        run = run_exported_script(
            backend=session.backend,
            command=session.command,
            script=running,
            cwd=run_directory,
            timeout=remaining,
            max_output_bytes=session.limits.cas_output_bytes,
        )
    except CasError as error:
        session.charge(time.monotonic() - started)
        return "failed", str(error)
    session.charge(time.monotonic() - started)

    # The file is read back, and put back if it moved. A verdict is a claim
    # about the bytes a reader will keep, so a run that rewrote them leaves no
    # such claim to make -- and leaves an artifact whose contents no longer
    # match the hash the manifest records for it, which is the export's own
    # promise about itself. Restoring costs nothing a reader wanted: the
    # published bytes are what this export set out to publish, and what the
    # run did to them is what the verdict now says.
    if not script.exists() or script.read_bytes() != published:
        put_back = (
            "the published bytes have been put back"
            if _restore_published(script, published)
            else "and the published bytes could not be put back, so what is on disk "
            "is not what this export's manifest describes"
        )
        return "failed", (
            "the published script rewrote itself while it was being run, so the "
            f"verdict would not describe the file this export publishes; {put_back}"
        )
    if run.timed_out:
        return "failed", f"the script did not finish within {remaining:g}s"
    if run.returncode:
        return "failed", f"the script exited {run.returncode}: {_excerpt(run.stderr.strip())}"

    # The file itself is what a line-oriented interpreter was fed, and what it
    # echoes back into its own transcript -- including Hardy's header and the
    # per-cell notes, which the session never printed and which sit between one
    # cell's output and the next.
    fed = (
        published.decode("utf-8", errors="replace")
        if getattr(session.backend, "script_stdin", False)
        else ""
    )
    stdout = session.backend.sanitize(run.stdout, fed)
    pattern = getattr(session.backend, "error_pattern", None)
    if pattern is not None and (pattern.search(stdout) or pattern.search(run.stderr)):
        # A sentinel interpreter reports an error and carries on with the next
        # line, so a broken script still exits 0. The banner is the exit code.
        return "failed", "the script printed an error banner"

    # Everything above is a claim the evidence supports whatever was truncated:
    # the file ran, it exited 0, and no banner appeared in what was read.
    # Comparing transcripts is not, and this is the point at which a missing
    # tail stops being survivable. `diverged` is as much an affirmative claim as
    # `verified` -- "the script printed something else" about bytes Hardy never
    # read is the same rounding-up the truncated-cell verdict refuses, pointed
    # the other way.
    if run.capture_truncated:
        return "unverified", (
            "the script's own output passed cas_output_bytes, so its transcript "
            "could not be compared against the record"
        )
    if truncated_cells:
        return "unverified", (
            f"cell(s) {truncated_cells} were recorded from a truncated capture, so "
            "there is no complete transcript to compare the script against"
        )

    expected_out, expected_err = _expected_transcript(cells)
    transcript = _between_markers(stdout)
    if transcript is not None and _wants_completion(session.backend):
        # Printed by the file's own last statement, so its absence says the
        # file did not get there. Checked before the transcript is compared,
        # because the comparison would otherwise pass: a run that stopped
        # after cell one prints exactly what cell one printed, and a run that
        # stopped before cell one prints nothing at all, which is what a
        # session of silent cells recorded.
        #
        # Presence is the whole of the claim, so the first occurrence is cut
        # out and the rest compared as usual -- rather than requiring it last,
        # which would misreport a cell's own `atexit` output as an early exit
        # when it is an ordinary divergence.
        if completion not in transcript:
            return "failed", (
                "the script stopped before it reached its last cell, so what it "
                "printed is not what running this file does"
            )
        transcript = transcript.replace(completion + "\n", "", 1).replace(completion, "", 1)
    if transcript is None:
        # The script exited 0 and its capture was complete, so the two
        # statements bracketing its own transcript are statements it ran. A
        # file that did not print them printed something other than what
        # Hardy wrote out.
        return "diverged", (
            "the script did not print the markers Hardy wrote around its own "
            f"transcript; it printed {_excerpt(run.stdout.strip())}"
        )
    trailing = _content_lines(_without_chrome(session.backend, _after_end_marker(stdout)))
    if trailing:
        return "diverged", (
            "the script printed after its own closing marker, which the session "
            f"never recorded: {_excerpt(trailing)}"
        )
    for stream, actual, expected in (
        ("output", transcript, expected_out),
        ("stderr", _without_chrome(session.backend, run.stderr), expected_err),
    ):
        got, want = _content_lines(actual), _content_lines(expected)
        if got != want:
            # The excerpts are here so a reader — or a CI log — can see *what*
            # differed without re-running anything. A verdict of "diverged" with
            # no evidence attached is another thing taken on trust. They are cut
            # to a readable size: a recorded line may be `cas_output_bytes` long,
            # and this detail is copied into export.json and the notebook, where
            # a verbatim pair of transcripts would dwarf the artifact.
            return "diverged", (
                f"the script's {stream} is not the {stream} the session recorded; "
                f"recorded {_excerpt(want)}, script printed {_excerpt(got)}"
            )
    if run.left_processes:
        # Last, because a concrete disagreement is worth more than this. What a
        # descendant printed *was* compared -- it arrives on the inherited
        # descriptor and is drained before anything is killed -- so a script
        # whose child contradicts the record is `diverged` on the evidence
        # rather than unverified for want of it. This is what is left when
        # everything comparable agreed: the run outlived itself, a descendant
        # with its own stdout is invisible to every check here, and one that
        # slept and then rewrote `sys.argv[0]` changed the artifact after the
        # verdict had been drawn on it. The group is killed before the file is
        # read back, so that race is closed; what running this file *does* is
        # still not bounded by what was seen of it.
        return "unverified", (
            "the script left a process running when it exited, so what running "
            "this file does is not bounded by what was observed of it"
        )
    return "verified", ""


def render_script(
    session: CasSession,
    cells: tuple[CellRecord, ...],
    verdicts: list[CellVerdict],
    completion: str = "",
) -> str:
    """Write the accepted cells out as a file that behaves the way they did.

    The header says what was checked and stops there. It cannot report the
    verdict on running this file, because the verdict is obtained by running
    exactly these bytes: a header that named its own result would describe a
    file that no longer existed by the time it was written. `export.json` and
    the notebook carry it instead, and the header points at them.
    """
    backend = session.backend
    mark = backend.comment
    replayed = sum(1 for verdict in verdicts if verdict.verdict == "verified")
    # Flattened for the same reason the per-cell notes below are: a version a
    # backend reported over more than one line would break the header out of
    # its comment exactly as a traceback broke the cell notes out of theirs.
    version = _one_line(session.version or "") or "unknown version"
    lines = [
        f"{mark} {WARNING}",
        f"{mark} backend: {backend.name} {version}",
        f"{mark} exported: {datetime.now(UTC).isoformat(timespec='seconds')}",
        f"{mark} cells: {len(cells)}; {replayed} of them reproduced when replayed"
        " one at a time in a fresh kernel.",
        f"{mark} Whether this file as a whole reproduces the session is a separate"
        " question: Hardy runs it and records the answer as `script_verdict` in"
        " export.json.",
        "",
    ]
    # The environment the session and the check both ran under. A verdict
    # describes running these bytes *this way*; run them another way and the
    # verdict is not about what you ran. `PYTHONHASHSEED` is the one that bites
    # in practice -- a cell printing a set or a string-keyed dict orders it by
    # the interpreter's per-process hash seed, so an unpinned reader can see a
    # different order from the one recorded and checked.
    environment = getattr(backend, "environment", {})
    if environment:
        setting = " ".join(f"{key}={value}" for key, value in sorted(environment.items()))
        lines += [
            f"{mark} Checked under {setting}. Run it the same way to get the",
            f"{mark} output Hardy compared against the session; a different hash",
            f"{mark} seed can reorder a printed set or dict. Also in export.json.",
            "",
        ]
    if backend.preamble:
        lines += [backend.preamble, ""]
    # The script says where its own transcript starts and stops, so the check
    # that compares it against the record does not have to guess which lines
    # the interpreter added around it. After the preamble, because a preamble
    # that printed anything printed it in the session's kernel too and the
    # session never recorded it.
    lines += [
        f"{mark} The statement(s) below, and any partner at the end of this file,",
        f"{mark} bracket what this file prints -- so Hardy can compare that against",
        f"{mark} the session without mistaking an interpreter's startup banner for",
        f"{mark} something a cell printed. See `script_verdict` in export.json.",
        *_markers(backend.transcript_prologue, completion),
        "",
    ]
    for record, verdict in zip(cells, verdicts, strict=True):
        note = (
            ""
            if verdict.verdict == "verified"
            else f"  [{verdict.verdict}: {_one_line(verdict.detail)}]"
        )
        lines.append(f"{mark} --- cell {record.seq} ({record.author}){note}")
        lines.append(backend.render_cell(record.source).rstrip())
        lines.append("")
    epilogue = _markers(backend.transcript_epilogue, completion)
    if epilogue:
        lines += [*epilogue, ""]
    return "\n".join(lines) + "\n"


def render_notebook(
    session: CasSession,
    cells: tuple[CellRecord, ...],
    verdicts: list[CellVerdict],
    script_verdict: tuple[Verdict, str] = ("unverified", "not run"),
) -> str:
    """nbformat v4, written directly.

    Hardy does not drive a Jupyter kernel — the Macaulay2 and Singular bridges
    are unmaintained — so the notebook is authored from the session's own
    record. For those backends the declared kernelspec may well name a kernel
    the reader does not have; it is a faithful record either way.
    """
    backend = session.backend
    notebook_cells: list[dict[str, Any]] = []
    for record, verdict in zip(cells, verdicts, strict=True):
        outputs: list[dict[str, Any]] = []
        if record.stdout:
            outputs.append(
                {"output_type": "stream", "name": "stdout", "text": record.stdout.splitlines(True)}
            )
        if record.stderr:
            outputs.append(
                {"output_type": "stream", "name": "stderr", "text": record.stderr.splitlines(True)}
            )
        if record.value_repr:
            outputs.append(
                {
                    "output_type": "execute_result",
                    "execution_count": record.seq,
                    "data": {"text/plain": record.value_repr.splitlines(True)},
                    "metadata": {},
                }
            )
        notebook_cells.append(
            {
                "cell_type": "code",
                "execution_count": record.seq,
                "metadata": {
                    "hardy": {
                        "seq": record.seq,
                        "author": record.author,
                        "verification": verdict.verdict,
                        "detail": verdict.detail,
                        "capture_truncated": record.capture_truncated,
                    }
                },
                "outputs": outputs,
                "source": record.source.splitlines(True),
            }
        )
    notebook = {
        "cells": notebook_cells,
        "metadata": {
            "hardy": {
                "warning": WARNING,
                "backend": backend.name,
                "version": session.version,
                # About the sibling script, not this notebook: the notebook
                # carries the recorded outputs and is honest by construction,
                # and a reader holding both should not have to open export.json
                # to find out which of the two was checked by execution.
                "script_verification": {
                    "verdict": script_verdict[0],
                    "detail": script_verdict[1],
                },
            },
            "kernelspec": {
                "display_name": backend.name,
                "language": backend.language,
                "name": backend.kernel_name,
            },
            "language_info": {"name": backend.language},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def export_session(session: CasSession, directory: Path) -> ExportReport:
    """Render, replay, compare, and publish the pair under one manifest."""
    cells = session.accepted()
    if not cells:
        raise CasError("nothing to export: the session has no accepted cells")

    # Every file this function publishes goes through this guard, which proves
    # at each write that `directory` is still the problem's own `cas/` and not
    # a symlink pointing out of it. `Layout.ensure` checked that when the
    # project opened; an export happens later, and a clone is free to ship the
    # link that makes "later" the interesting moment.
    guard = WriteGuard(directory, create=True)
    # Fresh every time, on the same rule `_verify_script` applies to
    # `script-run`: a replay that starts in the previous export's leftovers is
    # not the fresh kernel this check says it is, and a cell that writes a file
    # must be seen to create it rather than to find it.
    replay_directory = _scratch(directory, REPLAY)
    outcomes = replay_in_fresh_kernel(
        backend=session.backend,
        command=session.command,
        cells=cells,
        limits=session.limits,
        cwd=replay_directory,
        # An export is the session spending its own budget in a second kernel.
        # Bounded by what is left, and billed for what it uses, so a session
        # cannot exceed `cas_session_seconds` by exporting repeatedly. Cells
        # the remaining budget does not reach come back `unverified`, which is
        # what `docs/.../interactive-cas-design.md` already promised.
        budget_seconds=session.remaining_seconds,
        charge=session.charge,
    )
    verdicts = _verdicts(cells, outcomes, session.backend)

    script_path = directory / f"session{session.backend.script_suffix}"
    notebook_path = directory / "session.ipynb"
    # Fresh for this export, and known to both the file and the check.
    completion = completion_marker() if _wants_completion(session.backend) else ""
    script = render_script(session, cells, verdicts, completion).encode("utf-8")
    # The script is published before it is checked, because the thing checked
    # has to be the thing published: these exact bytes are what gets run.
    guard.write_bytes(script_path.name, script)
    try:
        script_verdict = _verify_script(session, cells, script_path, directory, completion)
    except Exception as error:  # noqa: BLE001 - see below
        # Deliberately everything. `DESIGN.md` requires a partial export to be
        # written and marked rather than withheld, and the check is the *last*
        # thing that should be able to take the notebook and the manifest with
        # it: a session that cannot say whether its script runs is strictly
        # better off than one with no artifacts at all. A verdict of
        # `unverified` naming the failure is what that costs.
        script_verdict = ("unverified", _excerpt(f"the script could not be checked: {error!r}"))
    notebook = render_notebook(session, cells, verdicts, script_verdict).encode("utf-8")
    guard.write_bytes(notebook_path.name, notebook)

    counts = {name: 0 for name in ("verified", "diverged", "failed", "unverified")}
    for verdict in verdicts:
        counts[verdict.verdict] += 1
    report = ExportReport(
        script_path=script_path.as_posix(),
        notebook_path=notebook_path.as_posix(),
        manifest_path=(directory / "export.json").as_posix(),
        backend=session.backend.name,
        verdicts=tuple(verdicts),
        script_verdict=script_verdict[0],
        script_detail=script_verdict[1],
        **counts,
    )
    # Written last, and recording both digests. Two atomic writes are not one
    # atomic write: a crash between them would leave a fresh script beside a
    # stale notebook, and only this manifest makes that detectable.
    manifest = {
        "exported_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "backend": session.backend.name,
        "version": session.version,
        # The environment the script was *checked* under, not a suggestion. A
        # verdict is a claim about running these bytes, and it only describes
        # what a reader gets if the reader runs them the same way -- which for
        # the default backend means `PYTHONHASHSEED=0`, since a set or a
        # string-keyed dict prints in a different order under a different seed.
        # Recorded here and named in the script's own header.
        "environment": dict(getattr(session.backend, "environment", {})),
        "counts": counts,
        "script_verdict": script_verdict[0],
        "script_detail": script_verdict[1],
        "files": {
            script_path.name: hashlib.sha256(script).hexdigest(),
            notebook_path.name: hashlib.sha256(notebook).hexdigest(),
        },
        "verdicts": [verdict.model_dump(mode="json") for verdict in verdicts],
    }
    guard.write_bytes(
        "export.json",
        (json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8"),
    )
    return report
