#!/usr/bin/env python3
"""Check the three ledgers against each other, the files, and the status rules.

    uv run --project /path/to/hardy python tools/check.py                # check, print the board
    uv run --project /path/to/hardy python tools/check.py --write-graphs # also refresh notes/dependency-graph.md

What it enforces, per problem:

- every assessed item carries a status from HARDY.md's vocabulary;
- no item assessed above `open` depends on an item that is `open`;
- the `depends_on`/`uses` graph is acyclic;
- every mirror of another problem's item names an item that still exists there
  with the same digest and status, and the problem graph itself is acyclic;
- every `lean_declaration` semantic names a declaration present in the problem's
  own `lean/` or the root's shared `.hardy/lean/`;
- every artifact reference still matches the bytes on disk;
- nothing is `lean verified` or `human verified`, since no evidence for either
  exists here yet; the day one is promoted, this line is the one to relax.

It reads the ledgers through Hardy's own store, so a damaged chain fails here
before it fails in a session. It never writes a ledger.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from collections import defaultdict
from pathlib import Path

from hardy.workflows.ledger.contracts import ProjectItem, ProjectItemKind, Relation, RelationKind
from hardy.workflows.ledger.store import LedgerStore

ROOT = Path(__file__).resolve().parents[1]
STATUSES = {"open", "llm proved", "human verified", "lean verified"}
INPUT_STATUSES = {"published input", "external research input", "imported"}
RANK = {"open": 0, "llm proved": 1, "human verified": 2, "lean verified": 3}
DECLARATION = re.compile(r"^\s*(?:axiom|theorem|lemma|def|abbrev|structure|constant|opaque|noncomputable def)\s+([A-Za-z_][A-Za-z0-9_'.]*)", re.M)
GRAPH = "notes/dependency-graph.md"


def problems() -> list[Path]:
    return sorted(p for p in ROOT.iterdir() if p.is_dir() and (p / "ledger").is_dir())


def lean_declarations(problem: Path) -> set[str]:
    names: set[str] = set()
    for tree in (problem / "lean", ROOT / ".hardy" / "lean"):
        for path in tree.rglob("*.lean"):
            names.update(DECLARATION.findall(path.read_text(encoding="utf-8")))
    return names


def status_of(item: ProjectItem) -> str | None:
    return item.research.status if item.research else None


def mermaid(problem: Path, items: dict[str, ProjectItem], relations: list[Relation]) -> str:
    classes = {"open": "open", "llm proved": "llm", "human verified": "human", "lean verified": "lean",
               "imported": "imported", "published input": "input", "external research input": "input"}
    lines = ["```mermaid", "flowchart LR", "%% prerequisite --> dependent; regenerated by tools/check.py --write-graphs",
             "classDef open fill:#f8d7da,stroke:#842029,color:#842029;",
             "classDef llm fill:#fff3cd,stroke:#997404,color:#664d03;",
             "classDef human fill:#cfe2ff,stroke:#084298,color:#052c65;",
             "classDef lean fill:#d1e7dd,stroke:#0f5132,color:#0a3622;",
             "classDef imported fill:#e2e3e5,stroke:#41464b,color:#41464b,stroke-dasharray: 4 2;",
             "classDef input fill:#f8f9fa,stroke:#adb5bd,color:#495057,stroke-dasharray: 2 2;"]
    used = {r.source.id for r in relations} | {r.target.id for r in relations}
    for id_, item in sorted(items.items()):
        if id_ not in used:
            continue
        node = id_.replace("-", "_").replace(":", "_")
        label = item.name.replace('"', "'")
        lines.append(f'  {node}["{id_}<br/>{label}"]')
        status = status_of(item)
        if status in classes:
            lines.append(f"  class {node} {classes[status]};")
    for rel in sorted(relations, key=lambda r: (r.target.id, r.source.id)):
        s, t = rel.source.id.replace("-", "_").replace(":", "_"), rel.target.id.replace("-", "_").replace(":", "_")
        arrow = "-->" if rel.kind == RelationKind.DEPENDS_ON else "-.->"
        lines.append(f"  {t} {arrow} {s}")
    lines.append("```")
    body = "\n".join(lines) + "\n"
    return (f"# Dependency graph: {problem.name}\n\n"
            "Generated from `ledger/` by `tools/check.py --write-graphs`; do not edit. Solid\n"
            "arrows are `depends_on`, dotted are `uses` (a published or external input).\n"
            "Colours are the item's recorded research status, which certifies nothing:\n"
            "red open, amber llm proved, blue human verified, green lean verified, grey a\n"
            "mirror of another problem's item, dotted grey a literature input.\n\n" + body)


def check(problem: Path, heads: dict[str, dict[str, ProjectItem]], write_graphs: bool) -> list[str]:
    errors: list[str] = []
    snapshot = LedgerStore(problem).read()
    items = {r.id: r for r in snapshot.current(ProjectItem)}
    relations = [r for r in snapshot.current(Relation) if r.kind in {RelationKind.DEPENDS_ON, RelationKind.USES}]
    heads[problem.name] = items
    declared = lean_declarations(problem)

    # Statuses and evidence.
    for id_, item in items.items():
        status = status_of(item)
        if status is None:
            continue
        if status not in STATUSES | INPUT_STATUSES:
            errors.append(f"{id_}: status {status!r} is not in the vocabulary")
        if status in {"lean verified", "human verified"}:
            errors.append(f"{id_}: {status} without a recorded evidence reference")
        for key, value in item.semantics:
            if key == "lean_declaration" and value.split(".")[-1] not in declared:
                errors.append(f"{id_}: lean_declaration {value} is not declared under lean/ or .hardy/lean/")
        for ref in item.artifacts:
            path = (problem / ref.uri).resolve()
            if not path.is_file():
                errors.append(f"{id_}: artifact {ref.uri} is missing")
            elif hashlib.sha256(path.read_bytes()).hexdigest() != ref.digest:
                errors.append(f"{id_}: artifact {ref.uri} changed since it was recorded")

    # Dependencies: direction, acyclicity, rank.
    edges: dict[str, set[str]] = defaultdict(set)
    for rel in relations:
        source, target = items.get(rel.source.id), items.get(rel.target.id)
        if source is None or target is None:
            errors.append(f"{rel.id}: relation endpoint is not a current item")
            continue
        edges[source.id].add(target.id)
        s_status, t_status = status_of(source), status_of(target)
        if rel.kind == RelationKind.DEPENDS_ON and s_status in RANK:
            effective = t_status
            if t_status == "imported":
                effective = dict(target.semantics).get("upstream_status")
            if effective in RANK and RANK[effective] == 0 and RANK[s_status] > 0:
                errors.append(f"{source.id} ({s_status}) depends on {target.id}, which is open")
        if rel.kind == RelationKind.USES and target.kind != ProjectItemKind.EXTERNAL_RESULT:
            errors.append(f"{source.id} uses {target.id}, which is not an external result")
    state: dict[str, int] = {}

    def visit(node: str, trail: tuple[str, ...]) -> None:
        if state.get(node) == 2:
            return
        if state.get(node) == 1:
            errors.append("dependency cycle: " + " -> ".join((*trail, node)))
            return
        state[node] = 1
        for nxt in sorted(edges.get(node, ())):
            visit(nxt, (*trail, node))
        state[node] = 2

    for node in sorted(items):
        visit(node, ())

    # Mirrors.
    for id_, item in items.items():
        if status_of(item) != "imported":
            continue
        meta = dict(item.semantics)
        upstream = meta.get("upstream_problem", "")
        if upstream not in heads:
            errors.append(f"{id_}: mirror names problem {upstream!r}, which is not checked before this one")
            continue
        source = heads[upstream].get(meta.get("upstream_item", id_))
        if source is None:
            errors.append(f"{id_}: mirror of an item {upstream} no longer holds")
        elif source.digest != meta.get("upstream_digest"):
            errors.append(f"{id_}: mirror is stale; {upstream} now holds {source.digest[:12]}")
        elif status_of(source) != meta.get("upstream_status"):
            errors.append(f"{id_}: upstream status moved to {status_of(source)!r}; refresh the mirror")

    # Graph file.
    rendered = mermaid(problem, items, relations)
    graph = problem / GRAPH
    if write_graphs:
        graph.write_text(rendered, encoding="utf-8")
    elif not graph.is_file() or graph.read_text(encoding="utf-8") != rendered:
        errors.append(f"{GRAPH} is out of date; run tools/check.py --write-graphs")

    # Board.
    counts: dict[str, int] = defaultdict(int)
    for item in items.values():
        counts[status_of(item) or f"({item.kind.value})"] += 1
    board = ", ".join(f"{k}: {v}" for k, v in sorted(counts.items()))
    print(f"{problem.name}: ledger revision {snapshot.revision}; {board}")
    return errors


def upstreams(problem: Path) -> set[str]:
    snapshot = LedgerStore(problem).read()
    return {dict(i.semantics).get("upstream_problem", "") for i in snapshot.current(ProjectItem)
            if i.research and i.research.status == "imported"}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--write-graphs", action="store_true", help="refresh each problem's notes/dependency-graph.md")
    args = parser.parse_args()
    # Upstream problems are checked first, so a mirror can be compared with its source.
    needs = {problem: upstreams(problem) for problem in problems()}
    ordered: list[Path] = []
    while needs:
        ready = [p for p, need in needs.items() if need <= {q.name for q in ordered}]
        if not ready:
            print("problem dependencies form a cycle: " + ", ".join(sorted(p.name for p in needs)))
            return 1
        for problem in ready:
            ordered.append(problem)
            del needs[problem]
    print("problem order: " + " -> ".join(p.name for p in ordered))
    heads: dict[str, dict[str, ProjectItem]] = {}
    failures: list[str] = []
    for problem in ordered:
        failures.extend(f"{problem.name}: {e}" for e in check(problem, heads, args.write_graphs))
    for failure in failures:
        print(failure)
    print("checks passed" if not failures else f"{len(failures)} check(s) failed")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
