"""Text observations record what the text prints, anchored, and infer nothing."""

from __future__ import annotations

from hardy.literature.sources.contracts import (
    AccessPolicy,
    DerivedRepresentation,
    ObservationKind,
    QualityProfile,
    RepresentationKind,
)
from hardy.literature.sources.observations import ObservationStore, observe_text

SHA = "a1" * 32

TEXT = (
    "Chapter 1. Groups\n"
    "1.1 Subgroups\n"
    "Definition 1.1. A subgroup is a subset closed under the operation.\n"
    "Theorem 1.2 (Lagrange). Every subgroup of a cyclic group is cyclic.\n"
    "Proof. Let H be a subgroup of Z. Then H is generated by its least element. ∎\n"
    "\f"
    "Proposition 1.3. By Theorem 1.2, every quotient of a cyclic group is cyclic.\n"
    "Proof of Proposition 1.3. Immediate.\n"
    "We have the identity\n"
    "x^2 = y (1.4)\n"
    "Theorem 1.8. A gap.\n"
)


def rep():
    return DerivedRepresentation(
        id="rep-norm", artifact_sha256=SHA, kind=RepresentationKind.NORMALIZED_TEXT, extractor="t", extractor_version="1",
        output_sha256="0" * 64, derived_at="2026-09-11T00:00:00+00:00", quality=QualityProfile(status="ok"),
        access=AccessPolicy.PRIVATE_LOCAL, payload_files=("text.txt",),
    )


def kinds(observations, kind):
    return [o for o in observations if o.kind is kind]


def test_statement_starts_record_explicit_numbers_only():
    found = observe_text(rep(), TEXT)
    starts = kinds(found, ObservationKind.STATEMENT_START)
    assert [(o.value("kind"), o.value("number"), o.value("number_origin")) for o in starts] == [
        ("definition", "1.1", "explicit"), ("theorem", "1.2", "explicit"), ("proposition", "1.3", "explicit"), ("theorem", "1.8", "explicit"),
    ]
    assert starts[1].value("name") == "Lagrange"
    assert all(o.anchor.locator.representation == "rep-norm" for o in starts)
    assert TEXT[starts[1].anchor.locator.start:].startswith("Theorem 1.2 (Lagrange).")


def test_unnumbered_statement_has_no_number_and_no_inference():
    found = observe_text(rep(), "Lemma. Something holds.\n")
    (start,) = kinds(found, ObservationKind.STATEMENT_START)
    assert start.value("number") == "" and start.value("number_origin") == "none"


def test_proof_markers_and_headings_and_page_breaks():
    found = observe_text(rep(), TEXT)
    assert [o.value("label") for o in kinds(found, ObservationKind.PROOF_START)] == ["Proof", "Proof"]
    assert len(kinds(found, ObservationKind.PROOF_END)) == 1
    headings = kinds(found, ObservationKind.HEADING)
    assert [(o.value("level"), o.value("number"), o.value("title")) for o in headings] == [("chapter", "1", "Groups"), ("subsection", "1.1", "Subgroups")]
    breaks = kinds(found, ObservationKind.PAGE_BREAK)
    assert len(breaks) == 1 and TEXT[breaks[0].anchor.locator.start] == "\f"


def test_references_exclude_the_heading_itself():
    found = observe_text(rep(), TEXT)
    refs = kinds(found, ObservationKind.REFERENCE)
    assert [(o.value("kind"), o.value("number")) for o in refs] == [("theorem", "1.2"), ("proposition", "1.3")]
    equations = kinds(found, ObservationKind.EQUATION_NUMBER)
    assert [o.value("number") for o in equations] == ["1.4"]


def test_observations_are_deterministic_and_sorted():
    assert observe_text(rep(), TEXT) == observe_text(rep(), TEXT)
    positions = [o.anchor.locator.start for o in observe_text(rep(), TEXT)]
    assert positions == sorted(positions)


def test_observation_store_is_write_once_per_set(tmp_path):
    store = ObservationStore(tmp_path / "trees")
    found = observe_text(rep(), TEXT)
    assert store.admit(SHA, "text-1", found) == found
    assert store.admit(SHA, "text-1", found[:1]) == found
    assert store.sets(SHA) == ("text-1",)
    assert store.get(SHA, "missing") == ()
    assert store.all(SHA) == found
